#!/bin/bash
# deploy_nvim.sh

set -e

# Determine the directory of the script (where the repo is)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/nvim"

TARGET_DIR="$HOME/.config/nvim"
TARGET_FILE="$TARGET_DIR/init.lua"

echo "Deploying Neovim configuration..."
echo "Source: $CONFIG_DIR"
echo "Target: $TARGET_FILE"

# Create target directory if it doesn't exist
if [ ! -d "$TARGET_DIR" ]; then
    echo "Creating directory: $TARGET_DIR"
    mkdir -p "$TARGET_DIR"
fi

# Backup existing init.lua if it exists
if [ -f "$TARGET_FILE" ]; then
    TIMESTAMP=$(date +%Y%m%d%H%M%S)
    BACKUP_FILE="$TARGET_FILE.bak.$TIMESTAMP"
    echo "Backing up existing init.lua to $BACKUP_FILE"
    mv "$TARGET_FILE" "$BACKUP_FILE"
fi

# Generate proxy config
# We simply point to the absolute path of the repo's nvim directory
cat > "$TARGET_FILE" <<EOF
-- Proxy init.lua generated by deploy_nvim.sh
-- Points to configuration in: $CONFIG_DIR

local config_path = "$CONFIG_DIR"

-- Prepend the configuration directory to the runtime path
vim.opt.rtp:prepend(config_path)

-- Execute the actual init.lua from the configuration directory
dofile(config_path .. "/init.lua")
EOF

echo "Deployment successful!"
echo "Neovim will now load configuration from: $CONFIG_DIR"
